{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "start segmentation.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "tiW14nEwzXjF"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "V8VgDWXV0Rio"
      },
      "source": [
        "# Prepare data and wandb"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QFsct5gh11Z_",
        "outputId": "75f1cfe6-2a7f-42fa-9c24-521a85ccbeae"
      },
      "source": [
        "! git clone https://colab:VRZN3BV8ipsGjJy2tyJL@gitlab.ethz.ch/dlproject/dlproject.git"
      ],
      "execution_count": 38,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "fatal: destination path 'dlproject' already exists and is not an empty directory.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jjvEW1ny2sMR",
        "outputId": "4671b891-8f01-4845-b638-5f75e35d24a8"
      },
      "source": [
        "!cd dlproject/src/ && bash download_data.sh"
      ],
      "execution_count": 42,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "download_data.sh: line 25: conda: command not found\n",
            "download_data.sh: line 26: conda: command not found\n",
            "\u001b[31mERROR: Invalid requirement: 'torch-1.9.0+cu111' (from line 10 of requirements.txt)\u001b[0m\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "W7D-6hK37zsm",
        "outputId": "1860ad87-2b7b-45ec-f890-0a9d194a6cd9"
      },
      "source": [
        "!ls dlproject"
      ],
      "execution_count": 30,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "cmd.txt  data  notebooks  README.md  src\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3bwvGQf12ve8",
        "outputId": "bcdac98b-642b-417f-8517-3ef3b62ca1b0"
      },
      "source": [
        "!cd dlproject/src && bash train.sh"
      ],
      "execution_count": 44,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "train.sh: line 4: conda: command not found\n",
            "Start training\n",
            "download_data.sh  prepare.sh\t    setup.py\t      train_one.sh\n",
            "mtl\t\t  requirements.txt  train_in_tmux.sh  train.sh\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
            "    \"__main__\", mod_spec)\n",
            "  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/dlproject/src/mtl/scripts/train.py\", line 10, in <module>\n",
            "    from pytorch_lightning import Trainer\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py\", line 62, in <module>\n",
            "    from pytorch_lightning import metrics\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py\", line 14, in <module>\n",
            "    from pytorch_lightning.metrics.classification import (  # noqa: F401\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py\", line 14, in <module>\n",
            "    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py\", line 18, in <module>\n",
            "    from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/functional/__init__.py\", line 14, in <module>\n",
            "    from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/functional/accuracy.py\", line 18, in <module>\n",
            "    from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/helpers.py\", line 19, in <module>\n",
            "    from pytorch_lightning.metrics.utils import select_topk, to_onehot\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py\", line 18, in <module>\n",
            "    from pytorch_lightning.utilities import rank_zero_warn\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py\", line 18, in <module>\n",
            "    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py\", line 28, in <module>\n",
            "    from torchtext.data import Batch\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/torchtext/__init__.py\", line 5, in <module>\n",
            "    from . import vocab\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/torchtext/vocab.py\", line 13, in <module>\n",
            "    from torchtext._torchtext import (\n",
            "ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory\n",
            "Terminate instance in 2 minutes. Use Ctrl+C to cancel the termination...\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "t2JVwfFn4ujX"
      },
      "source": [
        ""
      ],
      "execution_count": 33,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "v7v7Hccd7IWw"
      },
      "source": [
        ""
      ],
      "execution_count": 33,
      "outputs": []
    }
  ]
}